'use client';

import {
  Activity, AlertTriangle, BarChart3, Bot, Box, BrainCircuit, Camera,
  Check, ChevronRight, CircleDot, Clock3, Cpu, Database, Gauge, HardDrive,
  Layers3, LoaderCircle, Pause, Play, Plus, RefreshCw, Rocket, Search,
  Server, Settings2, ShieldCheck, Sparkles, X, Zap,
} from 'lucide-react';
import { useCallback, useEffect, useMemo, useState, type ReactNode } from 'react';
import { readAuthSession } from '@/lib/auth';
import styles from './models-management.module.css';

const API_BASE=(process.env.NEXT_PUBLIC_API_URL||'http://localhost:8000').replace(/\/$/,'');
type Stats={total_runs:number;completed_runs:number;failed_runs:number;average_processing_seconds:number|null;last_run_at:string|null;detections:number;violations:number;average_confidence:number|null};
type Model={code:string;name:string;version:string;type:'detection'|'classification';framework:string;connected:boolean;loaded:boolean;status:string;artifact_name:string|null;artifact_size_bytes:number|null;labels:string[];active_deployments:number;camera_coverage:number;stats:Stats};
type Deployment={id:string;model_code:string;model_name:string;camera_id:string;camera_code:string;camera_name:string;site_name:string;zone_name:string|null;confidence_threshold:number;is_enabled:boolean;deployed_at:string;stopped_at:string|null};
type CameraOption={id:string;code:string;name:string;site_name:string;zone_name:string|null;status:string};
type Run={id:number;model_name:string;camera_code:string|null;status:string;processing_time:number|null;prediction:string|null;confidence:number|null;created_at:string};
type ClassMetric={model_name:string;class_name:string;count:number;average_confidence:number};
type Daily={day:string;model_name:string;completed:number;failed:number;average_processing_seconds:number|null};
type Data={models:Model[];deployments:Deployment[];cameras:CameraOption[];recent_inferences:Run[];class_metrics:ClassMetric[];daily_metrics:Daily[];summary:{total_models:number;connected_models:number;loaded_models:number;active_deployments:number;cameras_covered:number;runs_24h:number;failures_24h:number;average_processing_seconds:number|null}};
function headers(json=false):HeadersInit{const x=readAuthSession();return{...(json?{'Content-Type':'application/json'}:{}),...(x?{Authorization:'Bearer '+x.session.access_token}:{})};}
function errorMessage(p:unknown){return p&&typeof p==='object'&&'detail'in p?String((p as {detail:unknown}).detail):'Không thể hoàn thành yêu cầu.';}
function size(value:number|null){if(value===null)return'—';const mb=value/1024/1024;return mb>1024?(mb/1024).toFixed(1)+' GB':Math.round(mb)+' MB';}
function time(value:string|null){return value?new Intl.DateTimeFormat('vi-VN',{dateStyle:'short',timeStyle:'short'}).format(new Date(value)):'Chưa chạy';}
function percent(value:number|null){return value===null?'—':Math.round(value*100)+'%';}
function Metric({icon,label,value,detail,tone='green'}:{icon:ReactNode;label:string;value:string|number;detail:string;tone?:string}){return <article className={styles.metric} data-tone={tone}><span>{icon}</span><div><small>{label}</small><strong>{value}</strong><em>{detail}</em></div></article>;}

export default function ModelsManagement(){
 const[data,setData]=useState<Data|null>(null),[selected,setSelected]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState(''),[toast,setToast]=useState(''),[query,setQuery]=useState(''),[deployOpen,setDeployOpen]=useState(false),[busy,setBusy]=useState(false);
 const load=useCallback(async()=>{setLoading(true);setError('');try{const r=await fetch(API_BASE+'/api/models/management',{headers:headers()});const p=await r.json().catch(()=>null);if(!r.ok)throw new Error(errorMessage(p));const result=p as Data;setData(result);setSelected(current=>current||result.models[0]?.code||'');}catch(e){setError(e instanceof Error?e.message:'Không thể tải mô hình.');}finally{setLoading(false);}},[]);
 useEffect(()=>{void load();},[load]);useEffect(()=>{if(!toast)return;const t=setTimeout(()=>setToast(''),3000);return()=>clearTimeout(t);},[toast]);
 const model=data?.models.find(x=>x.code===selected)||data?.models[0]||null;
 const deployments=useMemo(()=>data?.deployments.filter(x=>!model||x.model_code===model.code).filter(x=>!query||[x.camera_code,x.camera_name,x.site_name,x.zone_name||''].some(v=>v.toLocaleLowerCase('vi').includes(query.toLocaleLowerCase('vi'))))||[],[data,model,query]);
 async function action(path:string,body:unknown,success:string){setBusy(true);setError('');try{const r=await fetch(API_BASE+path,{method:'POST',headers:headers(true),body:JSON.stringify(body)});const p=await r.json().catch(()=>null);if(!r.ok)throw new Error(errorMessage(p));setToast(success);await load();return true;}catch(e){setError(e instanceof Error?e.message:'Không thể cập nhật mô hình.');return false;}finally{setBusy(false);}}
 if(loading)return <div className={styles.loading}><LoaderCircle/><strong>Đang đồng bộ Model Registry</strong><span>Đọc checkpoint, deployment và lịch sử inference...</span></div>;
 if(!data||!model)return <div className={styles.loading}><AlertTriangle/><strong>Không thể tải mô hình AI</strong><span>{error}</span><button onClick={()=>void load()}><RefreshCw size={15}/>Thử lại</button></div>;
 const successRate=model.stats.total_runs?Math.round(model.stats.completed_runs/model.stats.total_runs*100):0;
 return <div className={styles.page}>
  <header className={styles.heading}><div><span className={styles.eyebrow}><BrainCircuit size={13}/> AI MODEL OPERATIONS</span><h1>Mô hình AI</h1><p>Quản trị checkpoint, quan sát chất lượng và triển khai mô hình lên camera.</p></div><div className={styles.headActions}><button onClick={()=>void load()}><RefreshCw size={15}/>Đồng bộ</button><button onClick={()=>setDeployOpen(true)} disabled={!model.connected}><Rocket size={15}/>Triển khai mô hình</button></div></header>
  {error&&<div className={styles.error}><AlertTriangle size={15}/><span>{error}</span><button onClick={()=>setError('')}><X size={14}/></button></div>}
  <section className={styles.metrics}>
   <Metric icon={<BrainCircuit/>} label="Mô hình đã đăng ký" value={data.summary.total_models} detail={data.summary.connected_models+' checkpoint sẵn sàng'}/>
   <Metric icon={<Rocket/>} label="Triển khai hoạt động" value={data.summary.active_deployments} detail={data.summary.cameras_covered+' camera được phủ'} tone="blue"/>
   <Metric icon={<Zap/>} label="Inference 24 giờ" value={data.summary.runs_24h} detail={data.summary.failures_24h+' lần thất bại'} tone="orange"/>
   <Metric icon={<Clock3/>} label="Độ trễ trung bình" value={data.summary.average_processing_seconds===null?'—':data.summary.average_processing_seconds.toFixed(2)+'s'} detail="Các lần chạy hoàn tất" />
  </section>
  <section className={styles.registry}><header><div><span><Layers3 size={18}/></span><div><strong>Model Registry</strong><small>Checkpoint đang kết nối với backend</small></div></div><em>{data.summary.connected_models}/{data.summary.total_models} READY</em></header><div className={styles.modelCards}>{data.models.map(item=><button key={item.code} className={item.code===model.code?styles.modelCard+' '+styles.modelSelected:styles.modelCard} onClick={()=>setSelected(item.code)}><div className={styles.modelTop}><span data-type={item.type}>{item.type==='detection'?<Box/>:<Activity/>}</span><i data-ready={item.connected}>{item.connected?'READY':'OFFLINE'}</i></div><strong>{item.name}</strong><p>{item.type==='detection'?'Phát hiện đối tượng & PPE':'Phân loại hành vi trong video'}</p><dl><div><dt>Phiên bản</dt><dd>{item.version}</dd></div><div><dt>Triển khai</dt><dd>{item.active_deployments}</dd></div><div><dt>Lượt chạy</dt><dd>{item.stats.total_runs}</dd></div></dl><footer><span>{item.loaded?<><CircleDot/>Đã nạp RAM</>:<><Database/>Lazy loading</>}</span><ChevronRight size={15}/></footer></button>)}</div></section>
  <div className={styles.detailGrid}><section className={styles.detail}>
   <header className={styles.detailHead}><div className={styles.modelIdentity}><span data-type={model.type}>{model.type==='detection'?<Box/>:<Activity/>}</span><div><small>{model.code}</small><h2>{model.name}</h2><p>{model.framework}</p></div></div><div className={styles.ready} data-ready={model.connected}><i/><span><strong>{model.connected?'Sẵn sàng':'Chưa kết nối'}</strong><small>{model.loaded?'Đã nạp vào bộ nhớ':'Tải khi inference đầu tiên'}</small></span></div></header>
   <div className={styles.modelStats}><div><small>Tỷ lệ thành công</small><strong>{model.stats.total_runs?successRate+'%':'—'}</strong><span><i style={{width:successRate+'%'}}/></span></div><div><small>Độ tin cậy TB</small><strong>{percent(model.stats.average_confidence)}</strong></div><div><small>Phát hiện</small><strong>{model.stats.detections}</strong></div><div><small>Vi phạm</small><strong>{model.stats.violations}</strong></div></div>
   <div className={styles.meta}><div><HardDrive/><span><small>Checkpoint</small><strong>{model.artifact_name||'Chưa kết nối'}</strong></span><em>{size(model.artifact_size_bytes)}</em></div><div><Clock3/><span><small>Lần chạy gần nhất</small><strong>{time(model.stats.last_run_at)}</strong></span></div><div><Gauge/><span><small>Xử lý trung bình</small><strong>{model.stats.average_processing_seconds===null?'Chưa có dữ liệu':model.stats.average_processing_seconds.toFixed(2)+' giây'}</strong></span></div></div>
   <div className={styles.labels}><header><strong>Nhãn mô hình</strong><small>{model.labels.length} lớp được hỗ trợ</small></header><div>{model.labels.map((label,index)=><span key={label} data-alert={label.toLowerCase().includes('suspected')||label.toLowerCase().includes('violation')||label.toLowerCase().includes('unauthorized')||label.toLowerCase().includes('overload')}>{String(index+1).padStart(2,'0')} · {label}</span>)}</div></div>
  </section><Performance model={model} classes={data.class_metrics.filter(x=>x.model_name===model.name)} daily={data.daily_metrics.filter(x=>x.model_name===model.name)}/></div>
  <Deployments items={deployments} query={query} setQuery={setQuery} busy={busy} setOpen={()=>setDeployOpen(true)} toggle={(item)=>void action('/api/models/deployments/'+item.id+'/status',{is_enabled:!item.is_enabled},item.is_enabled?'Đã tạm dừng triển khai.':'Đã kích hoạt triển khai.') } threshold={(item,value)=>void action('/api/models/deployments/'+item.id+'/threshold',{confidence_threshold:value},'Đã cập nhật ngưỡng phát hiện.')}/>
  <RecentRuns runs={data.recent_inferences}/>
  {deployOpen&&<DeployModal model={model} cameras={data.cameras} deployments={data.deployments} busy={busy} close={()=>setDeployOpen(false)} submit={async(ids,threshold)=>{if(await action('/api/models/'+model.code+'/deploy',{camera_ids:ids,confidence_threshold:threshold},'Đã triển khai '+model.name+' thành công.'))setDeployOpen(false);}}/>}
  {toast&&<div className={styles.toast}><Check size={15}/>{toast}</div>}
 </div>;
}

function Performance({model,classes,daily}:{model:Model;classes:ClassMetric[];daily:Daily[]}){
 const max=Math.max(1,...classes.map(x=>x.count));
 const days=Array.from({length:7},(_,i)=>{const d=new Date();d.setDate(d.getDate()-(6-i));return d.toISOString().slice(0,10);});
 const map=new Map(daily.map(x=>[x.day,x]));
 const maxRuns=Math.max(1,...daily.map(x=>x.completed+x.failed));
 return <aside className={styles.performance}><header><div><span><BarChart3 size={17}/></span><div><strong>Hiệu năng mô hình</strong><small>Dữ liệu inference thực tế</small></div></div><em>7 NGÀY</em></header>
  <div className={styles.chart}><div className={styles.bars}>{days.map(day=>{const x=map.get(day),total=(x?.completed||0)+(x?.failed||0);return <div key={day} title={total+' lượt chạy'}><span style={{height:Math.max(total?10:2,total/maxRuns*100)+'%'}} data-empty={!total}/><small>{new Date(day+'T00:00:00').toLocaleDateString('vi-VN',{weekday:'short'})}</small></div>;})}</div>{daily.length===0&&<p>Chưa có inference trong 7 ngày</p>}</div>
  <div className={styles.distribution}><header><strong>Phân bố kết quả</strong><small>Top nhãn của {model.name}</small></header>{classes.length?classes.slice(0,6).map(x=><div key={x.class_name}><span><strong>{x.class_name}</strong><small>{x.count} · {percent(x.average_confidence)}</small></span><i><b style={{width:(x.count/max*100)+'%'}}/></i></div>):<div className={styles.noData}><Activity/><strong>Chưa có dữ liệu nhãn</strong><small>Chạy phân tích để bắt đầu đo lường.</small></div>}</div>
  <footer><span><Cpu/> Pipeline</span><strong>{model.type==='detection'?'Object detection':'Video classification'}</strong></footer>
 </aside>;
}

function Deployments({items,query,setQuery,busy,setOpen,toggle,threshold}:{items:Deployment[];query:string;setQuery:(v:string)=>void;busy:boolean;setOpen:()=>void;toggle:(x:Deployment)=>void;threshold:(x:Deployment,v:number)=>void}){
 const[editing,setEditing]=useState<string|null>(null),[value,setValue]=useState(.5);
 return <section className={styles.deployments}><header><div><span><Rocket size={18}/></span><div><strong>Triển khai camera</strong><small>Gán model và cấu hình ngưỡng theo từng nguồn hình</small></div></div><button onClick={setOpen}><Plus size={14}/>Thêm triển khai</button></header><div className={styles.tableTools}><label><Search size={14}/><input placeholder="Tìm camera hoặc khu vực..." value={query} onChange={e=>setQuery(e.target.value)}/></label><span>{items.filter(x=>x.is_enabled).length} đang hoạt động</span></div>
  <div className={styles.table}><div className={styles.tableHead}><span>Camera / vị trí</span><span>Mô hình</span><span>Ngưỡng</span><span>Triển khai lúc</span><span>Trạng thái</span><span/></div>{items.length?items.map(x=><div className={styles.row} key={x.id}><span className={styles.camera}><i><Camera size={15}/></i><p><strong>{x.camera_code} · {x.camera_name}</strong><small>{x.site_name} · {x.zone_name||'Chưa phân khu'}</small></p></span><span><strong>{x.model_name}</strong><small>{x.model_code}</small></span><span>{editing===x.id?<div className={styles.thresholdEdit}><input type="number" min=".1" max=".99" step=".01" value={value} onChange={e=>setValue(Number(e.target.value))}/><button disabled={busy} onClick={()=>{threshold(x,value);setEditing(null);}}><Check size={12}/></button></div>:<button className={styles.threshold} onClick={()=>{setEditing(x.id);setValue(x.confidence_threshold);}}>{Math.round(x.confidence_threshold*100)}% <Settings2 size={11}/></button>}</span><span><strong>{time(x.deployed_at)}</strong></span><span><i className={x.is_enabled?styles.live:styles.paused}/>{x.is_enabled?'Hoạt động':'Tạm dừng'}</span><span><button className={styles.iconButton} disabled={busy} onClick={()=>toggle(x)} title={x.is_enabled?'Tạm dừng':'Kích hoạt'}>{x.is_enabled?<Pause size={14}/>:<Play size={14}/>}</button></span></div>):<div className={styles.emptyTable}><Rocket/><strong>Chưa triển khai mô hình này</strong><p>Chọn “Thêm triển khai” để gán mô hình lên camera.</p><button onClick={setOpen}>Triển khai ngay</button></div>}</div>
 </section>;
}

function RecentRuns({runs}:{runs:Run[]}){return <section className={styles.runs}><header><div><span><Activity size={18}/></span><div><strong>Inference gần đây</strong><small>Lịch sử xử lý từ PostgreSQL</small></div></div><em>{runs.length} BẢN GHI</em></header><div className={styles.runList}>{runs.length?runs.slice(0,10).map(x=><article key={x.id}><span data-status={x.status}>{x.status==='completed'?<Check/>:x.status==='failed'?<X/>:<LoaderCircle/>}</span><div><strong>#{x.id} · {x.model_name}</strong><small>{x.camera_code||'Nguồn video kiểm thử'} · {time(x.created_at)}</small></div><p><strong>{x.prediction||'Chưa có kết quả'}</strong><small>{percent(x.confidence)}</small></p><em>{x.processing_time===null?'—':x.processing_time.toFixed(2)+'s'}</em></article>):<div className={styles.emptyRun}><Activity/><span><strong>Chưa có lịch sử inference</strong><small>Kết quả sẽ xuất hiện sau lần phân tích đầu tiên.</small></span></div>}</div></section>;}

function DeployModal({model,cameras,deployments,busy,close,submit}:{model:Model;cameras:CameraOption[];deployments:Deployment[];busy:boolean;close:()=>void;submit:(ids:string[],threshold:number)=>Promise<void>}){
 const[selected,setSelected]=useState<string[]>([]),[threshold,setThreshold]=useState(.5),[search,setSearch]=useState('');
 const active=new Set(deployments.filter(x=>x.model_code===model.code&&x.is_enabled).map(x=>x.camera_id));
 const visible=cameras.filter(x=>!search||[x.code,x.name,x.site_name,x.zone_name||''].some(v=>v.toLocaleLowerCase('vi').includes(search.toLocaleLowerCase('vi'))));
 function choose(id:string){setSelected(current=>current.includes(id)?current.filter(x=>x!==id):[...current,id]);}
 return <div className={styles.backdrop} onMouseDown={e=>{if(e.target===e.currentTarget)close();}}><section className={styles.modal}><header><span><Rocket/></span><div><small>MODEL DEPLOYMENT</small><h2>Triển khai {model.name}</h2><p>Chọn camera và ngưỡng phát hiện cho phiên bản {model.version}.</p></div><button onClick={close}><X/></button></header><div className={styles.modalBody}><div className={styles.deploySummary}><span data-type={model.type}>{model.type==='detection'?<Box/>:<Activity/>}</span><div><strong>{model.name}</strong><small>{model.framework}</small></div><em>{model.connected?'CHECKPOINT READY':'OFFLINE'}</em></div><label className={styles.cameraSearch}><Search/><input placeholder={`Tìm trong ${cameras.length} camera...`} value={search} onChange={e=>setSearch(e.target.value)}/></label><div className={styles.cameraChoices}>{visible.map(x=><button type="button" key={x.id} className={selected.includes(x.id)?styles.chosen:''} onClick={()=>choose(x.id)}><i>{selected.includes(x.id)&&<Check/>}</i><span><strong>{x.code} · {x.name}</strong><small>{x.site_name} · {x.zone_name||'Chưa phân khu'}</small></span><em data-online={x.status==='online'}>{active.has(x.id)?'Đang dùng':x.status}</em></button>)}</div><div className={styles.modalThreshold}><div><strong>Ngưỡng tin cậy</strong><output>{Math.round(threshold*100)}%</output></div><input type="range" min="10" max="99" value={Math.round(threshold*100)} onChange={e=>setThreshold(Number(e.target.value)/100)}/><small>Giá trị có thể chỉnh riêng cho từng camera sau khi triển khai.</small></div></div><footer><span><strong>{selected.length}</strong> camera đã chọn</span><div><button onClick={close}>Hủy</button><button disabled={!selected.length||busy} onClick={()=>void submit(selected,threshold)}>{busy?<LoaderCircle className={styles.spin}/>:<Rocket/>}Triển khai</button></div></footer></section></div>;
}
