'use client';

import {
  Activity, BellRing, Bot, Check, ChevronRight, Clock3, Database, HardDrive,
  History, Info, KeyRound, LoaderCircle, MonitorCog, RefreshCw, RotateCcw,
  Save, Server, Settings2, ShieldCheck, Sparkles, Users, X,
} from 'lucide-react';
import { useCallback, useEffect, useMemo, useState, type ReactNode } from 'react';
import { readAuthSession } from '@/lib/auth';
import styles from './settings-management.module.css';

const API_BASE=(process.env.NEXT_PUBLIC_API_URL||'http://localhost:8000').replace(/\/$/,'');
type SettingsData={
  general:{organization_name:string;timezone:string;language:'vi'|'en';date_format:'DD/MM/YYYY'|'MM/DD/YYYY'|'YYYY-MM-DD';time_format:'24h'|'12h';shift_start:string};
  ai:{inference_enabled:boolean;detection_confidence:number;minimum_event_interval_seconds:number;save_evidence:boolean;store_output_video:boolean;auto_create_critical_incident:boolean};
  alerts:{in_app_enabled:boolean;email_enabled:boolean;webhook_enabled:boolean;critical_immediate:boolean;digest_interval_minutes:5|15|30|60;escalation_minutes:number;quiet_hours_enabled:boolean;quiet_hours_start:string;quiet_hours_end:string};
  retention:{event_retention_days:number;evidence_retention_days:number;audit_retention_days:number;auto_cleanup_enabled:boolean};
  security:{session_timeout_minutes:number;require_mfa_for_admins:boolean;lockout_attempts:number;lockout_minutes:number;allow_password_login:boolean};
};
type Health={database:'healthy'|'degraded';backend:'healthy'|'degraded';cameras_total:number;cameras_online:number;models_registered:number;events_total:number;open_alerts:number;active_users:number;checked_at:string};
type Audit={id:number;action:string;actor_name:string|null;created_at:string;changed_sections:string[]};
type Response={organization_id:string;organization_code:string;settings:SettingsData;health:Health;recent_changes:Audit[];updated_at:string};
type Tab='general'|'ai'|'alerts'|'retention'|'security'|'activity';
const TABS=[
  ['general','Tổ chức & hiển thị','Đơn vị, ngôn ngữ, múi giờ',Settings2],
  ['ai','AI & phát hiện','Ngưỡng, bằng chứng, tự động hóa',Bot],
  ['alerts','Cảnh báo','Kênh gửi và quy tắc ưu tiên',BellRing],
  ['retention','Lưu trữ dữ liệu','Vòng đời sự kiện và bằng chứng',HardDrive],
  ['security','Bảo mật','Phiên, khóa tài khoản và MFA',ShieldCheck],
  ['activity','Nhật ký thay đổi','Theo dõi cấu hình quản trị',History],
] as const;
const LABELS:Record<string,string>={general:'Tổ chức & hiển thị',ai:'AI & phát hiện',alerts:'Cảnh báo',retention:'Lưu trữ dữ liệu',security:'Bảo mật'};
function headers(json=false):HeadersInit{const s=readAuthSession();return{...(json?{'Content-Type':'application/json'}:{}),...(s?{Authorization:'Bearer '+s.session.access_token}:{})};}
function message(payload:unknown){if(payload&&typeof payload==='object'&&'detail'in payload){const d=(payload as {detail:unknown}).detail;if(typeof d==='string')return d;if(Array.isArray(d))return d.map(x=>x&&typeof x==='object'&&'msg'in x?String(x.msg):String(x)).join(', ');}return'Không thể hoàn thành yêu cầu.';}
function date(value:string){return new Intl.DateTimeFormat('vi-VN',{dateStyle:'medium',timeStyle:'short'}).format(new Date(value));}
function Field({label,hint,children}:{label:string;hint?:string;children:ReactNode}){return <label className={styles.field}><span>{label}</span>{children}{hint&&<small>{hint}</small>}</label>;}
function Toggle({value,set,title,text,badge}:{value:boolean;set:(v:boolean)=>void;title:string;text:string;badge?:string}){return <button type="button" className={value?styles.toggle+' '+styles.on:styles.toggle} onClick={()=>set(!value)}><span><strong>{title}{badge&&<em>{badge}</em>}</strong><small>{text}</small></span><i><b/></i></button>;}
function Panel({title,text,icon,children}:{title:string;text:string;icon:ReactNode;children:ReactNode}){return <section className={styles.panel}><header><span>{icon}</span><div><strong>{title}</strong><small>{text}</small></div></header><div className={styles.body}>{children}</div></section>;}
function Title({icon,title,text}:{icon:ReactNode;title:string;text:string}){return <div className={styles.title}><span>{icon}</span><div><h2>{title}</h2><p>{text}</p></div></div>;}

export default function SettingsManagement(){
  const[data,setData]=useState<Response|null>(null),[form,setForm]=useState<SettingsData|null>(null);
  const[base,setBase]=useState(''),[tab,setTab]=useState<Tab>('general'),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(''),[toast,setToast]=useState('');
  const load=useCallback(async()=>{setLoading(true);setError('');try{const r=await fetch(API_BASE+'/api/settings',{headers:headers()});const p=await r.json().catch(()=>null);if(!r.ok)throw new Error(message(p));const d=p as Response;setData(d);setForm(d.settings);setBase(JSON.stringify(d.settings));}catch(e){setError(e instanceof Error?e.message:'Không thể tải cấu hình.');}finally{setLoading(false);}},[]);
  useEffect(()=>{void load();},[load]);useEffect(()=>{if(!toast)return;const t=window.setTimeout(()=>setToast(''),3000);return()=>clearTimeout(t);},[toast]);
  const dirty=useMemo(()=>!!form&&!!base&&JSON.stringify(form)!==base,[form,base]);
  useEffect(()=>{const fn=(e:BeforeUnloadEvent)=>{if(dirty)e.preventDefault();};addEventListener('beforeunload',fn);return()=>removeEventListener('beforeunload',fn);},[dirty]);
  function update<S extends keyof SettingsData,K extends keyof SettingsData[S]>(s:S,k:K,v:SettingsData[S][K]){setForm(f=>f?{...f,[s]:{...f[s],[k]:v}}:f);}
  async function save(){if(!form||!dirty||saving)return;setSaving(true);setError('');try{const r=await fetch(API_BASE+'/api/settings',{method:'POST',headers:headers(true),body:JSON.stringify(form)});const p=await r.json().catch(()=>null);if(!r.ok)throw new Error(message(p));const d=(p as {settings:Response}).settings;setData(d);setForm(d.settings);setBase(JSON.stringify(d.settings));setToast('Đã lưu và áp dụng cấu hình hệ thống.');}catch(e){setError(e instanceof Error?e.message:'Không thể lưu cấu hình.');}finally{setSaving(false);}}
  async function reset(){if(!confirm('Khôi phục toàn bộ chính sách về mặc định?'))return;setSaving(true);try{const r=await fetch(API_BASE+'/api/settings/reset',{method:'POST',headers:headers(true)});const p=await r.json().catch(()=>null);if(!r.ok)throw new Error(message(p));const d=(p as {settings:Response}).settings;setData(d);setForm(d.settings);setBase(JSON.stringify(d.settings));setToast('Đã khôi phục cấu hình mặc định.');}catch(e){setError(e instanceof Error?e.message:'Không thể khôi phục.');}finally{setSaving(false);}}
  if(loading)return <div className={styles.loading}><LoaderCircle/><strong>Đang tải cấu hình hệ thống</strong><span>Kiểm tra chính sách của tổ chức...</span></div>;
  if(!data||!form)return <div className={styles.loading}><Server/><strong>Không thể mở cấu hình</strong><span>{error}</span><button onClick={()=>void load()}>Thử lại</button></div>;
  const status=[
    ['Backend API',data.health.backend==='healthy'?'Ổn định':'Gián đoạn',Server,data.health.backend==='healthy'],
    ['PostgreSQL',data.health.database==='healthy'?'Đã kết nối':'Mất kết nối',Database,data.health.database==='healthy'],
    ['Camera trực tuyến',data.health.cameras_online+'/'+data.health.cameras_total,Activity,data.health.cameras_total===0||data.health.cameras_online>0],
    ['Mô hình đăng ký',String(data.health.models_registered),Sparkles,data.health.models_registered>0],
  ] as const;
  return <div className={styles.page}>
    <header className={styles.heading}><div><span className={styles.eyebrow}><MonitorCog size={13}/> QUẢN TRỊ NỀN TẢNG</span><h1>Cấu hình hệ thống</h1><p>Thiết lập chính sách vận hành chung cho <strong>{form.general.organization_name}</strong>.</p></div><div className={styles.actions}><button onClick={()=>void reset()} disabled={saving}><RotateCcw size={15}/>Khôi phục mặc định</button><button onClick={()=>void save()} disabled={!dirty||saving}>{saving?<LoaderCircle className={styles.spin}/>:<Save size={15}/>}Lưu thay đổi</button></div></header>
    {error&&<div className={styles.error}><Info size={15}/><span>{error}</span><button onClick={()=>setError('')}><X size={14}/></button></div>}
    <section className={styles.health}><div className={styles.healthIntro}><span><ShieldCheck/></span><div><strong>Trạng thái nền tảng</strong><small>Cập nhật {date(data.health.checked_at)}</small></div></div><div className={styles.healthGrid}>{status.map(([label,value,Icon,ok])=><div key={label}><span data-ok={ok}><Icon size={15}/></span><p><small>{label}</small><strong>{value}</strong></p></div>)}</div><button onClick={()=>void load()}><RefreshCw size={15}/></button></section>
    <div className={styles.layout}><aside className={styles.tabs}><div className={styles.org}><span>{form.general.organization_name.slice(0,2).toUpperCase()}</span><div><small>Tổ chức hiện tại</small><strong>{form.general.organization_name}</strong><em>{data.organization_code}</em></div></div><nav>{TABS.map(([id,label,text,Icon])=><button key={id} className={tab===id?styles.active:''} onClick={()=>setTab(id)}><span><Icon size={17}/></span><div><strong>{label}</strong><small>{text}</small></div><ChevronRight size={14}/></button>)}</nav><div className={styles.note}><Info size={14}/><p><strong>Phạm vi áp dụng</strong><span>Chỉ tổ chức hiện tại; mọi thay đổi đều được ghi nhật ký.</span></p></div></aside>
    <main className={styles.main}>
      {tab==='general'&&<General form={form} code={data.organization_code} update={update}/>}
      {tab==='ai'&&<AI form={form} update={update}/>}
      {tab==='alerts'&&<Alerts form={form} update={update}/>}
      {tab==='retention'&&<Retention form={form} update={update}/>}
      {tab==='security'&&<Security form={form} update={update}/>}
      {tab==='activity'&&<ActivityLog data={data}/>}
    </main></div>
    {dirty&&<div className={styles.unsaved}><span><i/><strong>Có thay đổi chưa lưu</strong><small>Cấu hình chưa được áp dụng.</small></span><div><button onClick={()=>{setForm(JSON.parse(base) as SettingsData);setError('');}}>Hủy thay đổi</button><button onClick={()=>void save()}><Save size={14}/>Lưu và áp dụng</button></div></div>}
    {toast&&<div className={styles.toast}><Check size={15}/>{toast}</div>}
  </div>;
}

type Updater=<S extends keyof SettingsData,K extends keyof SettingsData[S]>(s:S,k:K,v:SettingsData[S][K])=>void;
function General({form,code,update}:{form:SettingsData;code:string;update:Updater}){return <><Title icon={<Settings2/>} title="Tổ chức & hiển thị" text="Thông tin nhận diện và quy ước thời gian cho toàn bộ dashboard."/><Panel title="Thông tin tổ chức" text="Tên hiển thị trong dashboard, báo cáo và thông báo." icon={<Settings2/>}><div className={styles.form}><Field label="Tên tổ chức"><input value={form.general.organization_name} onChange={e=>update('general','organization_name',e.target.value)}/></Field><Field label="Mã tổ chức" hint="Mã định danh không thể chỉnh sửa."><input value={code} disabled/></Field><Field label="Ngôn ngữ"><select value={form.general.language} onChange={e=>update('general','language',e.target.value as 'vi'|'en')}><option value="vi">Tiếng Việt</option><option value="en">English</option></select></Field></div></Panel><Panel title="Múi giờ & định dạng" text="Áp dụng cho cảnh báo, sự cố và báo cáo." icon={<Clock3/>}><div className={styles.form}><Field label="Múi giờ"><select value={form.general.timezone} onChange={e=>update('general','timezone',e.target.value)}><option value="Asia/Ho_Chi_Minh">Asia/Ho_Chi_Minh (UTC+7)</option><option value="Asia/Bangkok">Asia/Bangkok (UTC+7)</option><option value="Asia/Singapore">Asia/Singapore (UTC+8)</option><option value="UTC">UTC</option></select></Field><Field label="Định dạng ngày"><select value={form.general.date_format} onChange={e=>update('general','date_format',e.target.value as SettingsData['general']['date_format'])}><option>DD/MM/YYYY</option><option>MM/DD/YYYY</option><option>YYYY-MM-DD</option></select></Field><Field label="Định dạng giờ"><select value={form.general.time_format} onChange={e=>update('general','time_format',e.target.value as '24h'|'12h')}><option value="24h">24 giờ</option><option value="12h">12 giờ (AM/PM)</option></select></Field><Field label="Bắt đầu ca mặc định"><input type="time" value={form.general.shift_start} onChange={e=>update('general','shift_start',e.target.value)}/></Field></div></Panel></>;}
function AI({form,update}:{form:SettingsData;update:Updater}){return <><Title icon={<Bot/>} title="AI & phát hiện" text="Điều chỉnh độ nhạy, bằng chứng và hành vi tự động của pipeline AI."/><Panel title="Trạng thái xử lý" text="Kiểm soát phân tích và lưu bằng chứng toàn hệ thống." icon={<Sparkles/>}><div className={styles.toggles}><Toggle value={form.ai.inference_enabled} set={v=>update('ai','inference_enabled',v)} title="Cho phép phân tích AI" text="Bật xử lý RF-DETR và VideoMAE." badge="CỐT LÕI"/><Toggle value={form.ai.save_evidence} set={v=>update('ai','save_evidence',v)} title="Lưu ảnh bằng chứng" text="Lưu JPG tại khung hình tốt nhất."/><Toggle value={form.ai.store_output_video} set={v=>update('ai','store_output_video',v)} title="Lưu video kết quả" text="Lưu video đã vẽ vùng nhận diện."/><Toggle value={form.ai.auto_create_critical_incident} set={v=>update('ai','auto_create_critical_incident',v)} title="Tự tạo sự cố critical" text="Mở phiếu khi phát hiện cảnh báo nghiêm trọng."/></div></Panel><Panel title="Ngưỡng phát hiện" text="Ngưỡng thấp nhạy hơn nhưng có thể tăng cảnh báo sai." icon={<Settings2/>}><div className={styles.range}><div><strong>Độ tin cậy tối thiểu</strong><output>{Math.round(form.ai.detection_confidence*100)}%</output></div><input type="range" min="10" max="99" value={Math.round(form.ai.detection_confidence*100)} onChange={e=>update('ai','detection_confidence',Number(e.target.value)/100)}/><footer><span>Nhạy hơn</span><span>Khuyến nghị 50–75%</span><span>Chính xác hơn</span></footer></div><div className={styles.half}><Field label="Khoảng cách tối thiểu giữa hai sự kiện" hint="Giảm cảnh báo trùng từ cùng camera."><div className={styles.suffix}><input type="number" min="5" max="3600" value={form.ai.minimum_event_interval_seconds} onChange={e=>update('ai','minimum_event_interval_seconds',Number(e.target.value))}/><span>giây</span></div></Field></div></Panel></>;}

function Alerts({form,update}:{form:SettingsData;update:Updater}){return <><Title icon={<BellRing/>} title="Cảnh báo & thông báo" text="Chọn kênh nhận thông tin và cách ưu tiên cảnh báo quan trọng."/><Panel title="Kênh thông báo" text="Phải bật ít nhất một kênh tiếp nhận." icon={<BellRing/>}><div className={styles.channels}><Channel title="Trong ứng dụng" text="Trung tâm thông báo dashboard" status="Sẵn sàng" value={form.alerts.in_app_enabled} set={v=>update('alerts','in_app_enabled',v)}/><Channel title="Email" text="Gửi tới người nhận theo quy tắc" status="Cần SMTP" value={form.alerts.email_enabled} set={v=>update('alerts','email_enabled',v)}/><Channel title="Webhook" text="Tích hợp hệ thống bên thứ ba" status="Cần endpoint" value={form.alerts.webhook_enabled} set={v=>update('alerts','webhook_enabled',v)}/></div></Panel><Panel title="Chính sách gửi" text="Tổng hợp, nâng cấp và khung giờ yên lặng." icon={<Clock3/>}><div className={styles.toggles}><Toggle value={form.alerts.critical_immediate} set={v=>update('alerts','critical_immediate',v)} title="Gửi critical ngay lập tức" text="Bỏ qua lịch tổng hợp với cảnh báo nghiêm trọng."/><Toggle value={form.alerts.quiet_hours_enabled} set={v=>update('alerts','quiet_hours_enabled',v)} title="Bật khung giờ yên lặng" text="Tạm hoãn cảnh báo không khẩn cấp."/></div><div className={styles.form+' '+styles.separated}><Field label="Tần suất tổng hợp"><select value={form.alerts.digest_interval_minutes} onChange={e=>update('alerts','digest_interval_minutes',Number(e.target.value) as 5|15|30|60)}><option value="5">5 phút</option><option value="15">15 phút</option><option value="30">30 phút</option><option value="60">60 phút</option></select></Field><Field label="Nâng cấp sau"><div className={styles.suffix}><input type="number" min="1" max="1440" value={form.alerts.escalation_minutes} onChange={e=>update('alerts','escalation_minutes',Number(e.target.value))}/><span>phút</span></div></Field><Field label="Yên lặng từ"><input type="time" disabled={!form.alerts.quiet_hours_enabled} value={form.alerts.quiet_hours_start} onChange={e=>update('alerts','quiet_hours_start',e.target.value)}/></Field><Field label="Đến"><input type="time" disabled={!form.alerts.quiet_hours_enabled} value={form.alerts.quiet_hours_end} onChange={e=>update('alerts','quiet_hours_end',e.target.value)}/></Field></div></Panel></>;}
function Channel({title,text,status,value,set}:{title:string;text:string;status:string;value:boolean;set:(v:boolean)=>void}){return <button type="button" className={value?styles.channel+' '+styles.channelOn:styles.channel} onClick={()=>set(!value)}><span><BellRing size={17}/></span><div><strong>{title}</strong><p>{text}</p><small>{status}</small></div><i>{value&&<Check size={12}/>}</i></button>;}

function Retention({form,update}:{form:SettingsData;update:Updater}){return <><Title icon={<HardDrive/>} title="Lưu trữ dữ liệu" text="Kiểm soát thời gian lưu dữ liệu vận hành và bằng chứng."/><div className={styles.blueNote}><Database/><div><strong>Chính sách vòng đời dữ liệu</strong><p>Dữ liệu hết hạn chỉ được xóa khi tác vụ dọn dẹp bật. Sự cố đang mở được bảo vệ.</p></div></div><Panel title="Thời gian lưu giữ" text="Tính theo ngày kể từ thời điểm tạo dữ liệu." icon={<Database/>}><div className={styles.retention}><RetentionBox title="Sự kiện & cảnh báo" text="Phát hiện, trạng thái và xử lý." value={form.retention.event_retention_days} min={30} set={v=>update('retention','event_retention_days',v)}/><RetentionBox title="Ảnh & video bằng chứng" text="Tệp kết quả phân tích AI." value={form.retention.evidence_retention_days} min={7} set={v=>update('retention','evidence_retention_days',v)}/><RetentionBox title="Nhật ký kiểm toán" text="Thao tác quản trị và bảo mật." value={form.retention.audit_retention_days} min={90} set={v=>update('retention','audit_retention_days',v)}/></div><div className={styles.separated}><Toggle value={form.retention.auto_cleanup_enabled} set={v=>update('retention','auto_cleanup_enabled',v)} title="Tự động dọn dữ liệu hết hạn" text="Cho phép tác vụ nền áp dụng chính sách lưu trữ."/></div></Panel></>;}
function RetentionBox({title,text,value,min,set}:{title:string;text:string;value:number;min:number;set:(v:number)=>void}){return <div className={styles.retentionBox}><span><Database size={17}/></span><strong>{title}</strong><p>{text}</p><label><input type="number" min={min} max="3650" value={value} onChange={e=>set(Number(e.target.value))}/><em>ngày</em></label><small>≈ {Math.max(1,Math.round(value/30))} tháng</small></div>;}

function Security({form,update}:{form:SettingsData;update:Updater}){return <><Title icon={<ShieldCheck/>} title="Bảo mật & truy cập" text="Chính sách phiên đăng nhập và bảo vệ tài khoản quản trị."/><Panel title="Chính sách đăng nhập" text="Áp dụng cho lần xác thực tiếp theo." icon={<KeyRound/>}><div className={styles.toggles}><Toggle value={form.security.allow_password_login} set={v=>update('security','allow_password_login',v)} title="Cho phép đăng nhập bằng mật khẩu" text="Giữ phương thức email và mật khẩu hiện tại."/><Toggle value={form.security.require_mfa_for_admins} set={v=>update('security','require_mfa_for_admins',v)} title="Yêu cầu MFA cho quản trị viên" text="Chính sách cho bước tích hợp xác thực nhiều lớp." badge="NÂNG CAO"/></div><div className={styles.form+' '+styles.separated}><Field label="Thời hạn phiên"><div className={styles.suffix}><input type="number" min="15" max="1440" value={form.security.session_timeout_minutes} onChange={e=>update('security','session_timeout_minutes',Number(e.target.value))}/><span>phút</span></div></Field><Field label="Khóa sau số lần sai"><div className={styles.suffix}><input type="number" min="3" max="10" value={form.security.lockout_attempts} onChange={e=>update('security','lockout_attempts',Number(e.target.value))}/><span>lần</span></div></Field><Field label="Thời gian khóa"><div className={styles.suffix}><input type="number" min="5" max="1440" value={form.security.lockout_minutes} onChange={e=>update('security','lockout_minutes',Number(e.target.value))}/><span>phút</span></div></Field></div></Panel><div className={styles.security}><span><ShieldCheck/></span><div><strong>Mức bảo vệ hiện tại</strong><p>{form.security.require_mfa_for_admins?'Nâng cao':'Tiêu chuẩn'} · Khóa sau {form.security.lockout_attempts} lần sai · Phiên {form.security.session_timeout_minutes} phút</p></div><em>{form.security.require_mfa_for_admins?'NÂNG CAO':'TIÊU CHUẨN'}</em></div></>;}

function ActivityLog({data}:{data:Response}){return <><Title icon={<History/>} title="Nhật ký thay đổi" text="Các lần cập nhật cấu hình gần nhất của tổ chức."/><Panel title="Hoạt động quản trị" text="Dữ liệu trực tiếp từ audit_logs và không thể chỉnh sửa." icon={<History/>}><div className={styles.audit}>{data.recent_changes.length?data.recent_changes.map(x=><article key={x.id}><span><History size={15}/></span><div><strong>{x.action==='settings.reset'?'Khôi phục cấu hình mặc định':'Cập nhật cấu hình hệ thống'}</strong><p>{x.changed_sections.length?x.changed_sections.map(s=>LABELS[s]||s).join(' · '):'Không có nhóm dữ liệu thay đổi'}</p></div><aside><strong>{x.actor_name||'Hệ thống'}</strong><small>{date(x.created_at)}</small></aside></article>):<div className={styles.empty}><History/><strong>Chưa có thay đổi nào</strong><p>Lần lưu đầu tiên sẽ xuất hiện tại đây.</p></div>}</div></Panel><div className={styles.metrics}><Metric icon={<Users/>} label="Người dùng hoạt động" value={data.health.active_users}/><Metric icon={<BellRing/>} label="Cảnh báo đang mở" value={data.health.open_alerts}/><Metric icon={<Database/>} label="Tổng sự kiện" value={data.health.events_total}/></div></>;}
function Metric({icon,label,value}:{icon:ReactNode;label:string;value:number}){return <div><span>{icon}</span><p><small>{label}</small><strong>{value}</strong></p></div>;}
